version: "3"
services:
  web:
    image: node:latest
    volumes:
     - .:/app
    networks:
     - default
     - nginx
    restart: always
    working_dir: /app/src
    command: "bash -c 'yarn && yarn watch'"
    environment:
      KNWST_TZ: America/New_York
  redis:
    image: redis:7.4.2-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis:/data:Z
    restart: always
    command: "redis-server /usr/local/etc/redis/redis.conf"
  db:
    image: mariadb:11.3.2-jammy
    volumes:
      - ./mariadb:/var/lib/mysql:Z
    restart: always
    environment:
      MARIADB_DATABASE: knwst
      MARIADB_USER: knwst
      MARIADB_PASSWORD: knwst
      MARIADB_ROOT_PASSWORD: password
  adminer:
    image: adminer
    networks:
     - default
     - nginx
    environment: 
      ADMINER_PLUGINS: adminer-bypass
    volumes:
      - ./adminer-bypass.php:/var/www/html/plugins/adminer-bypass.php:ro
    restart: always

# nginx network is managed externally on kuilin's server
# forwards incoming requests to containers on the network
# your setup may vary of course
networks:
  nginx:
    external: true
