// thanks https://parade.com/951718/parade/anxiety-quotes/
// manually filtered to remove the ones i don't like

const anxiety = [
  `"No need to hurry. No need to sparkle. No need to be anybody but oneself." -Virginia Woolf`,
  `"Stress is an ignorant state. It believes that everything is an emergency. Nothing is that important." -Natalie Goldberg`,
  `"I just give myself permission to suck... I find this hugely liberating." -John Green`,
  `"We must have a pie. Stress cannot exist in the presence of a pie." -David Mamet`,
  `"Anxiety is a thin stream of fear trickling through the mind. If encouraged, it cuts a channel into which all other thoughts are drained." -Arthur Somers Roche`,
  `"Nothing diminishes anxiety faster than action." -Walter Anderson`,
  `"Your mind will answer most questions if you learn to relax and wait for the answer." -William S. Burroughs`,
  `"Not everything that weighs you down is yours to carry." -Anonymous`,
  `"Do what you can, with what you've got, where you are." -Theodore Roosevelt`,
  `"Anxiety's like a rocking chair. It gives you something to do, but it doesn't get you very far." -Jodi Picoult`,
  `"Life is ten percent what you experience and ninety percent how you respond to it." -Anonymous`,
  `"Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor." -Thich Nhat Hanh`,
  `"You don't have to control your thoughts; you just have to stop letting them control you." -Dan Millman`,
  `"People become attached to their burdens sometimes more than the burdens are attached to them." -George Bernard Shaw`,
  `"It's not time to worry yet." -Harper Lee`,
  `"Almost everything will work again if you unplug it for a few minutes, including you." -Anne Lamott`,
  `"My anxiety doesn't come from thinking about the future but from wanting to control it." -Hugh Prather`,
  `"If you don't like something, change it. If you can't change it, change your attitude." -Maya Angelou`,
  `"The way you tell your story to yourself matters." -Amy Cuddy`,
  `"Worry often gives a small thing a big shadow." -Swedish proverb`,
  `"It's not stress that kills us, it is our reaction to it." -Hans Selye`,
  `"Nothing can bring you peace but yourself." -Ralph Waldo Emerson`,
  `"The time to relax is when you don't have time for it." -Sydney J. Harris`,
  `"When you feel overwhelmed, remember: A little at a time is how it gets done. One thing, one task, one moment at a time." -Anonymous`,
  `"Surrender to what is, let go of what was, and have faith in what will be." -Sonia Ricotti`,
  `"Calm mind brings inner strength and self-confidence, so that's very important for good health." -Dalai Lama`,
  `"You wouldn't worry so much about what others think of you if you realized how seldom they do." -Attributed to Eleanor Roosevelt`,
  `"Present fears are less than horrible imaginings." -William Shakespeare`,
  `"You have dug your soul out of the dark, you have fought to be here; do not go back to what buried you." -Bianca Sparacino`,
  `"Everyone remembers the remark of the old man at the point of death, that his life had been full of troubles-most of which had never happened." -Winston Churchill`,
  `"Rule number one: Don't sweat the small stuff. Rule number two: It's all small stuff." -Robert S. Eliot`,
  `"Sometimes letting things go is an act of far greater power than defending or hanging on." -Eckhart Tolle`,
  `"The universe doesn't allow perfection." -Stephen Hawking`,
  `"A crust eaten in peace is better than a banquet partaken in anxiety." -Aesop`,
  `"What else does anxiety about the future bring you but sorrow upon sorrow?" -Thomas a Kempis`,
  `"Nothing is permanent in this wicked world-not even our troubles." -Charlie Chaplin`,
  `"For us, there is only the trying. The rest is not our business." -T.S. Eliot`,
  `"Actually spending ten minutes clearing off one shelf is better than fantasizing about spending a weekend cleaning out the basement." -Gretchen Rubin`,
  `"We must be willing to get rid of the life we've planned, so as to have the life that is waiting for us." -Joseph Campbell`,
  `"We live only a few conscious decades, and we fret ourselves enough for several lifetimes." -Christopher Hitchens`,
  `"Happiness is not a brilliant climax to years of grim struggle and anxiety. It is a long succession of little decisions simply to be happy in the moment." -J. Donald Walters`,
  `"In the end, just three things matter: How well we have lived. How well we have loved. How well we have learned to let go." -Jack Kornfield`,
  `"There must be quite a few things that a hot bath won't cure, but I don't know many of them." -Sylvia Plath`,
  `"What lies behind us and what lies before us are tiny matters compared to what lies within us." -Henry Stanley Haskins`,
  `"There is no chance, no destiny, no fate, that can circumvent or hinder or control the firm resolve of a determined soul." -Ella Wheeler Wilcox`,
  `"You don't drown by falling into water. You only drown if you stay there." -Zig Ziglar`,
  `"Grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference." -Reinhold Niebuhr`,
  `"In order to move on, you must understand why you felt what you did and why you no longer need to feel it." -Mitch Albom`,
  `"Anxiety happens when you think you have to figure out everything all at once. Breathe. You're strong. You got this. Take it day by day." -Karen Salmansohn`,
  `"Calmness is the cradle of power." -Josiah Gilbert Holland`,
  `"Don't underestimate the value of Doing Nothing, of just going along, listening to all the things you can't hear, and not bothering." -A.A. Milne`,
  `"Anxiety is a lot like a toddler. It never stops talking, tells you you're wrong about everything, and wakes you up at 3 am." -Anonymous`,
  `"There are two ways to get rid of an anxiety monster, my friend- you either have a bath or a nap." -Andrew Kaufman`,
  `"Don't let yesterday take up too much of today." -Anonymous`,
  `"The best thing one can do when it is raining, is to let it rain." -Henry Wadsworth Longfellow`,
  `"You cannot make yourself feel something you do not feel, but you can make yourself do right in spite of your feelings." -Pearl S. Buck`,
  `"He who fears he shall suffer, already suffers what he fears." -Michel de Montaigne`,
  `"The greatest mistake we make is living in constant fear that we will make one." -John C. Maxwell`,
  `"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it." -Henry Ford`,
  `"Don't believe every worried thought you have. Worried thoughts are notoriously inaccurate." -Renee Jain`,
  `"You can't go back and make a new start, but you can start right now and make a brand new ending." -James R. Sherman`,
  `"Those who mind don't matter and those who matter don't mind." -Anonymous`,
  `"If you can find a path with no obstacles, it probably doesn't lead anywhere." -Frank A. Clark`
];

const getQuote = () => anxiety[Math.floor(Math.random()*anxiety.length)];

module.exports = {getQuote};
